### Listar todos os cachorros
GET http://localhost:3000/cachorros
Accept: application/json
Content-Type: application/json

### Inserir cachorro
POST http://localhost:3000/cachorros
Accept: application/json
Content-Type: application/json

{
    "nome": "Rex",
    "raca": "Labrador",
    "idade": 3,
    "peso": 20.5,
    "cor": "Amarelo"
}

### Atualizar cachorro
PUT http://localhost:3000/cachorros/1
Accept: application/json
Content-Type: application/json

{
    "nome": "Buddy",
    "raca": "Golden Retriever",
    "idade": 5,
    "peso": 30.0,
    "cor": "Dourado"
}

### Obter cachorro específico
GET http://localhost:3000/cachorros/1
Accept: application/json
Content-Type: application/json

### Deletar cachorro
DELETE http://localhost:3000/cachorros/1
Accept: application/json
Content-Type: application/json